#!/usr/bin/env php
<?php


foreach (array(__DIR__ . '/../../../autoload.php', __DIR__ . '/../vendor/autoload.php') as $file) {
    if (file_exists($file)) {
        define('CI_TOOL_COMPOSER_AUTOLOADER', $file);
        break;
    }
}

require CI_TOOL_COMPOSER_AUTOLOADER;
require __DIR__ . '/bootstrap.php';

use CITool\Commands\CommandFactory;

$command = $argv[1];

try {
    /** @var CommandFactory $cmdFactory */
    $cmdFactory = $container->get(CommandFactory::class);
    $cmd = $cmdFactory->create($command);
    $code = $cmd->execute();
    exit($code);
} catch (\Throwable $e) {
    echo $e->getMessage() . PHP_EOL;
    exit(1);
}